In [16]:
pip install numpy

In [17]:
import numpy as np


In [18]:
l1 = [2,3,54, 7]

In [19]:
arr = np.arry(l1)

AttributeError: module 'numpy' has no attribute 'arry'

2D arrys


In [56]:
arr2 = np.arange(1, 10).reshape((3,3))

In [57]:
arr2.shape

(3, 3)

In [58]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
arr2.ndim

2

In [60]:
arr2.dtype

dtype('int32')

In [61]:
arr2.size

9

In [62]:
np.arange(1 , 21).reshape((4, 5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [63]:
arr3.saphe

AttributeError: 'numpy.ndarray' object has no attribute 'saphe'

In [ ]:
np.zeros((4, 4), dtype = 'int' )

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
np.ones( (3, 4), dtype= complax )

NameError: name 'complax' is not defined

In [ ]:
np.arange(1, 20,5)

array([ 1,  6, 11, 16])

In [ ]:
np.linspace(10, 25, 20)

array([10.        , 10.78947368, 11.57894737, 12.36842105, 13.15789474,
       13.94736842, 14.73684211, 15.52631579, 16.31578947, 17.10526316,
       17.89473684, 18.68421053, 19.47368421, 20.26315789, 21.05263158,
       21.84210526, 22.63157895, 23.42105263, 24.21052632, 25.        ])

numpy operaters

In [65]:
arr2 = 5

In [1]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.
